### ISSUE TITLE
GUI interface for attendance sheet

### ISSUE THREAD

**Issue by lakshaydeepak** [lakshaydeepak/attendee-profiler#13]

**Comment by abhi-198** [comment]
We can add both present and absent student in the attendance sheet separately  in the same window

**Comment by ayush-goel311** [comment]
The suggestion is nice thank you for this . I have also added the checkbuttons just like in our college's attendance sheet.

**Comment by abhi-198** [comment]
use gird for alignment of labels and entry it will be more systematic and easy to use for further modification for adding student.

**Comment by abhi-198** [comment]
All done now, it is working right, only percentage of student is remaining to display on it after fetching records from database.
